-- MySQL Script generated by MySQL Workbench
-- Sat Feb 16 10:16:58 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sisfo_akper
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sisfo_akper
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sisfo_akper` DEFAULT CHARACTER SET utf8 ;
USE `sisfo_akper` ;

-- -----------------------------------------------------
-- Table `sisfo_akper`.`tahun_ajaran`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisfo_akper`.`tahun_ajaran` (
  `id_tahun_ajaran` INT NOT NULL AUTO_INCREMENT,
  `tahun_ajarancol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tahun_ajaran`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisfo_akper`.`pmb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisfo_akper`.`pmb` (
  `id_pmb` INT NOT NULL AUTO_INCREMENT,
  `nama_lengkap` VARCHAR(191) NULL,
  `email` VARCHAR(191) NULL,
  `password` VARCHAR(191) NULL,
  `kewarganegaraan` ENUM('WNI', 'WNA') NULL,
  `jk` ENUM('L', 'P') NULL,
  `tinggi_badan` DOUBLE NULL,
  `berat_badan` DOUBLE NULL,
  `alamat` MEDIUMTEXT NULL,
  `kode_pos` VARCHAR(10) NULL,
  `tmpt_lahir` VARCHAR(100) NULL,
  `tgl_lahir` DATE NULL,
  `nama_ayah` VARCHAR(100) NULL,
  `nama_ibu` VARCHAR(100) NULL,
  `no_hp1` VARCHAR(15) NULL,
  `no_hp2` VARCHAR(15) NULL,
  `info_dari` VARCHAR(45) NULL,
  `nama_asal_sekolah` VARCHAR(100) NULL,
  `alamat_asal_sekolah` VARCHAR(100) NULL,
  `foto_diri` MEDIUMTEXT NULL,
  `foto_ijazah` MEDIUMTEXT NULL,
  `foto_kesehatan` MEDIUMTEXT NULL,
  `validasi_pembayaran` ENUM('0', '1') NULL DEFAULT '0',
  `first_time_login` ENUM('0', '1') NULL DEFAULT '1',
  `level` ENUM('pmb_baru', 'pmb_lamah') NULL DEFAULT 'pmb_baru',
  `is_active` ENUM('0', '1') NULL DEFAULT '1',
  `no_peserta` VARCHAR(45) NULL,
  `is_lulus` ENUM('0', '1') NULL,
  `tahun_ajaran_id_tahun_ajaran` INT NOT NULL,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `no_peserta_UNIQUE` (`no_peserta` ASC),
  PRIMARY KEY (`id_pmb`),
  INDEX `fk_pmb_tahun_ajaran1_idx` (`tahun_ajaran_id_tahun_ajaran` ASC),
  CONSTRAINT `fk_pmb_tahun_ajaran1`
    FOREIGN KEY (`tahun_ajaran_id_tahun_ajaran`)
    REFERENCES `sisfo_akper`.`tahun_ajaran` (`id_tahun_ajaran`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisfo_akper`.`mahasiswa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisfo_akper`.`mahasiswa` (
  `id_mahasiswa` INT NOT NULL AUTO_INCREMENT,
  `nama_lengkap` VARCHAR(191) NULL,
  `email` VARCHAR(191) NULL,
  `password` VARCHAR(191) NULL,
  `kewarganegaraan` ENUM('WNI', 'WNA') NULL,
  `jk` ENUM('L', 'P') NULL,
  `tinggi_badan` DOUBLE NULL,
  `berat_badan` DOUBLE NULL,
  `alamat` MEDIUMTEXT NULL,
  `kode_pos` VARCHAR(10) NULL,
  `tmpt_lahir` VARCHAR(100) NULL,
  `tgl_lahir` DATE NULL,
  `nama_ayah` VARCHAR(100) NULL,
  `nama_ibu` VARCHAR(100) NULL,
  `no_hp1` VARCHAR(15) NULL,
  `no_hp2` VARCHAR(15) NULL,
  `info_dari` VARCHAR(45) NULL,
  `nama_asal_sekolah` VARCHAR(100) NULL,
  `alamat_asal_sekolah` VARCHAR(100) NULL,
  `foto_diri` MEDIUMTEXT NULL,
  `foto_ijazah` MEDIUMTEXT NULL,
  `foto_kesehatan` MEDIUMTEXT NULL,
  `validasi_pembayaran` ENUM('0', '1') NULL DEFAULT '0',
  `first_time_login` ENUM('0', '1') NULL DEFAULT '1',
  `level` ENUM('pmb_baru', 'pmb_lamah') NULL DEFAULT 'pmb_baru',
  `id_tahun_ajaran` INT NOT NULL,
  `tahun_masuk` INT NOT NULL,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  PRIMARY KEY (`id_mahasiswa`),
  INDEX `fk_mahasiswa_tahun_ajaran1_idx` (`id_tahun_ajaran` ASC),
  INDEX `fk_mahasiswa_tahun_ajaran2_idx` (`tahun_masuk` ASC),
  CONSTRAINT `fk_mahasiswa_tahun_ajaran1`
    FOREIGN KEY (`id_tahun_ajaran`)
    REFERENCES `sisfo_akper`.`tahun_ajaran` (`id_tahun_ajaran`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mahasiswa_tahun_ajaran2`
    FOREIGN KEY (`tahun_masuk`)
    REFERENCES `sisfo_akper`.`tahun_ajaran` (`id_tahun_ajaran`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisfo_akper`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisfo_akper`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(150) NULL,
  `password` VARCHAR(191) NULL,
  `is_active` ENUM('0', '1') NULL DEFAULT '1',
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sisfo_akper`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisfo_akper`.`role` (
  `id_role` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_role`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sisfo_akper`.`role_has_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisfo_akper`.`role_has_user` (
  `id_role` INT NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_role`, `id_user`),
  INDEX `fk_role_has_user_user1_idx` (`id_user` ASC),
  INDEX `fk_role_has_user_role_idx` (`id_role` ASC),
  CONSTRAINT `fk_role_has_user_role`
    FOREIGN KEY (`id_role`)
    REFERENCES `sisfo_akper`.`role` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_has_user_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `sisfo_akper`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sisfo_akper`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisfo_akper`.`menu` (
  `id_menu` INT NOT NULL AUTO_INCREMENT,
  `menu_code` VARCHAR(150) NOT NULL,
  `menu_name` VARCHAR(150) NULL,
  `is_parent` ENUM('0', '1') NULL DEFAULT '1',
  `parent_id` INT(11) NULL,
  PRIMARY KEY (`id_menu`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sisfo_akper`.`menu_has_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisfo_akper`.`menu_has_role` (
  `id_menu` INT NOT NULL,
  `id_role` INT NOT NULL,
  PRIMARY KEY (`id_menu`, `id_role`),
  INDEX `fk_menu_has_role_role1_idx` (`id_role` ASC),
  INDEX `fk_menu_has_role_menu1_idx` (`id_menu` ASC),
  CONSTRAINT `fk_menu_has_role_menu1`
    FOREIGN KEY (`id_menu`)
    REFERENCES `sisfo_akper`.`menu` (`id_menu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menu_has_role_role1`
    FOREIGN KEY (`id_role`)
    REFERENCES `sisfo_akper`.`role` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sisfo_akper`.`mapel_pmb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisfo_akper`.`mapel_pmb` (
  `id_mapel_pmb` INT NOT NULL AUTO_INCREMENT,
  `mapel_pmb_code` VARCHAR(45) NOT NULL,
  `mapel_pmb_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_mapel_pmb`),
  UNIQUE INDEX `mapel_pmb_code_UNIQUE` (`mapel_pmb_code` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sisfo_akper`.`nilai_ujian_pmb`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisfo_akper`.`nilai_ujian_pmb` (
  `id_nilai_ujian_pmb` INT NOT NULL AUTO_INCREMENT,
  `nilai` DOUBLE NOT NULL,
  `id_pmb` INT NOT NULL,
  `id_mapel_pmb` INT NOT NULL,
  PRIMARY KEY (`id_nilai_ujian_pmb`),
  INDEX `fk_nilai_ujian_pmb_pmb1_idx` (`id_pmb` ASC),
  INDEX `fk_nilai_ujian_pmb_mapel_pmb1_idx` (`id_mapel_pmb` ASC),
  CONSTRAINT `fk_nilai_ujian_pmb_pmb1`
    FOREIGN KEY (`id_pmb`)
    REFERENCES `sisfo_akper`.`pmb` (`id_pmb`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nilai_ujian_pmb_mapel_pmb1`
    FOREIGN KEY (`id_mapel_pmb`)
    REFERENCES `sisfo_akper`.`mapel_pmb` (`id_mapel_pmb`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
